//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Property
    {
        public int PropertyId { get; set; }
        public string TypeOfProperty { get; set; }
        public string District { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Area { get; set; }
        public string TypeOfContrusction { get; set; }
        public string PhoneNumber { get; set; }
        public string AdditionalInformation { get; set; }
        public string ApprovalStatus { get; set; } = "Not Approved";
        public Nullable<bool> Deleted { get; set; } = false;
        public Nullable<bool> Sold { get; set; } = false;
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual PropertyVisualDetail PropertyVisualDetail { get; set; }
    }
}
