//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyDetailsTemplates = new HashSet<PropertyDetailsTemplate>();
        }
    
        public int PropertyId { get; set; }
        public string TypeOfProperty { get; set; }
        public string District { get; set; }
        public string Neighbourhood { get; set; }
        public int Price { get; set; }
        public int Area { get; set; }
        public string TypeOfConstruction { get; set; }
        public string PhoneNumber { get; set; }
        public string AdditionalInformation { get; set; }
        public string ApprovalStatus { get; set; } = "Not Approved";
        public string TypeOfSale { get; set; }
        public bool Deleted { get; set; }
        public bool WantToBuy { get; set; }
        public bool Sold { get; set; }
        public string PropertyDetailsTable { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyDetailsTemplate> PropertyDetailsTemplates { get; set; }
        public virtual UserProperty UserProperty { get; set; }
    }
}
