//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyVisualDetail
    {
        public int PropertyId { get; set; }
        public string CoordinatesOfVTour { get; set; }
        public string Image { get; set; }
        public string Video { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual User User { get; set; }
    }
}
