//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyDetailsTemplates = new HashSet<PropertyDetailsTemplate>();
        }
    
        public int PropertyId { get; set; }

        [Display(Name = "Вид на имота")]
        public string TypeOfProperty { get; set; }

        [Display(Name = "Град")]
        public string District { get; set; }

        [Display(Name = "Квартал")]
        public string Neighbourhood { get; set; }

        [Display(Name = "Цена")]
        public int Price { get; set; }

        [Display(Name = "Квадратура")]
        public int Area { get; set; }

        [Display(Name = "Тип на строителство")]
        public string TypeOfConstruction { get; set; }

        [Display(Name = "Телефонен номер")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Допълнително информация")]
        public string AdditionalInformation { get; set; }

        [Display(Name = "Статус на одобрение")]
        public string ApprovalStatus { get; set; } = "Not Approved";

        [Display(Name = "Тип на обявата")]
        public string TypeOfSale { get; set; }

        [Display(Name = "Изтрит ли е?")]
        public bool Deleted { get; set; }

        [Display(Name = "Купува ли се?")]
        public bool WantToBuy { get; set; }

        [Display(Name = "Продаден ли е?")]
        public bool Sold { get; set; }
        public string PropertyDetailsTable { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyDetailsTemplate> PropertyDetailsTemplates { get; set; }
        public virtual UserProperty UserProperty { get; set; }
    }
}
