//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Staff
    {
        public int UserId { get; set; }
        [DisplayName("Ниво на потребител")]
        public string UserLevel { get; set; }
    
        public virtual User User { get; set; }
    }
}
