//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Properties = new HashSet<Property>();
            this.PropertyVisualDetails = new HashSet<PropertyVisualDetail>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "First name:")]
        [MaxLength(50, ErrorMessage = "First name must be at most 50 characters long.")]
        [MinLength(3, ErrorMessage = "First name must be at least 3 characters long.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "First name must contain only letters.")]
        public string FirstName { get; set; }


        [Required(ErrorMessage = "Last name is required.")]
        [Display(Name = "Last name:")]
        [MaxLength(50, ErrorMessage = "Last name must be at most 50 characters long.")]
        [MinLength(3, ErrorMessage = "Last name must be at least 3 characters long.")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Last name must contain only letters.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Email is required.")]
        [Display(Name = "Email:")]
        [MaxLength(100, ErrorMessage = "Email must be at most 100 characters long.")]
        [MinLength(4, ErrorMessage = "Email must be at least 4 characters long.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        [Display(Name = "Password:")]
        [MaxLength(400, ErrorMessage = "Password must be at most 400 characters long.")]
        [MinLength(8, ErrorMessage = "Password must be at least 8 characters long.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [NotMapped]
        [Required(ErrorMessage = "This field is required!")]
        [Display(Name = "Reenter your password:")]
        [DataType(DataType.Password)]
        public string RePassword { get; set; }
        public Nullable<bool> Deleted { get; set; } = false;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyVisualDetail> PropertyVisualDetails { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
