//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualVistaHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Properties = new HashSet<Property>();
            this.PropertyDetailsTemplates = new HashSet<PropertyDetailsTemplate>();
            this.Properties1 = new HashSet<Property>();
        }
    
        public int UserId { get; set; }
        [Display(Name = "First name:")]
        [MaxLength(50, ErrorMessage = "First name must be at most 50 characters long.")]
        [MinLength(3, ErrorMessage = "First name must be at least 3 characters long.")]
        public string FirstName { get; set; }

        [Display(Name = "Last name:")]
        [MaxLength(50, ErrorMessage = "Last name must be at most 50 characters long.")]
        [MinLength(3, ErrorMessage = "Last name must be at least 3 characters long.")]
        public string LastName { get; set; }

        [Display(Name = "Email:")]
        [MaxLength(100, ErrorMessage = "Email must be at most 100 characters long.")]
        [MinLength(4, ErrorMessage = "Email must be at least 4 characters long.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }

        [Display(Name = "Password:")]
        [MaxLength(400, ErrorMessage = "Password must be at most 400 characters long.")]
        [MinLength(7, ErrorMessage = "Password must be at least 8 characters long.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [NotMapped]
        [Display(Name = "Reenter your password:")]
        [DataType(DataType.Password)]
        public string RePassword { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyDetailsTemplate> PropertyDetailsTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Properties1 { get; set; }
    }
}
